language: python
python:
 - "2.7"
sudo: required
before_install:
 - "ifconfig"
 - "sudo apt-get update -qq"
 - "sudo apt-get install tcpdump libpcap0.8-dev libnetfilter-queue-dev libssl-dev"

install: "pip install -r requirements.txt"
script: nosetests